import {readFileSync, readdirSync} from 'node:fs';
import path from 'node:path';
import type {LoadedContent, SidebarsConfig} from '@docusaurus/plugin-content-docs';
import type {Plugin} from '@docusaurus/types';

type SidebarItemConfig = Extract<SidebarsConfig[string], unknown[]>[number];

interface CategoryMetadata {
  label: string;
  position?: number;
  collapsed?: boolean;
  customProps?: {route?: string};
  link: {type: 'doc'; id: string} | {type: 'generated-index'; slug?: string};
}

interface NavigationLink {
  label: string;
  to: string;
}

interface Collection extends NavigationLink {
  directory: string;
  docId: string;
  collapsed: boolean;
}

function categories(directory: string) {
  return readdirSync(path.join(__dirname, 'docs', directory), {withFileTypes: true})
    .filter(entry => entry.isDirectory())
    .map(entry => ({
      directory: path.posix.join(directory, entry.name),
      metadata: JSON.parse(readFileSync(
        path.join(__dirname, 'docs', directory, entry.name, '_category_.json'), 'utf8',
      )) as CategoryMetadata,
    }))
    .sort((left, right) => (left.metadata.position ?? Infinity) - (right.metadata.position ?? Infinity)
      || left.directory.localeCompare(right.directory));
}

export const collections: Collection[] = [
  ...categories('courses'),
  ...categories('').filter(({metadata}) => metadata.link?.type === 'doc'),
].map(({directory, metadata}) => {
  if (metadata.link.type !== 'doc') {
    throw new Error(`Navigation collection ${directory} requires a doc landing page`);
  }
  const docDirectory = directory.split('/').map(segment => segment.replace(/^\d+[-_]/, '')).join('/');
  return {
    directory,
    label: metadata.label,
    to: metadata.customProps?.route ?? `/courses/${path.posix.basename(directory)}`,
    docId: metadata.link.id.startsWith(`${docDirectory}/`)
      ? metadata.link.id : `${docDirectory}/${metadata.link.id}`,
    collapsed: metadata.collapsed ?? true,
  };
});

function collection(directory: string): Collection {
  const result = collections.find(entry => entry.directory === directory);
  if (!result) throw new Error(`Missing navigation collection ${directory}`);
  return result;
}

const books = collection('books');
const calculator = collection('calculator');
const courses = collections.filter(entry => entry.directory.startsWith('courses/'));
const courseGroup = JSON.parse(readFileSync(
  path.join(__dirname, 'docs/courses/_category_.json'), 'utf8',
)) as {label: string; collapsed?: boolean};
const allContents: NavigationLink = {label: 'All contents', to: '/'};
export const navigation = [
  {label: courseGroup.label, collections: courses},
  {label: books.label, collections: [books], to: books.to},
  {label: calculator.label, collections: [calculator], to: calculator.to},
];

function collectionSidebar(entry: Collection): SidebarItemConfig {
  return {
    type: 'category',
    label: entry.label,
    collapsed: false,
    link: {type: 'doc', id: entry.docId},
    items: [{type: 'autogenerated', dirName: entry.directory}],
  };
}

export const navigationSidebars: SidebarsConfig = {
  journeySidebar: [
    {type: 'doc', label: allContents.label, id: 'home'},
    ...navigation.flatMap((group): SidebarItemConfig[] => group.to
      ? [{type: 'link', label: group.label, href: group.to}]
      : [{
        type: 'category',
        label: group.label,
        collapsed: courseGroup.collapsed ?? false,
        items: group.collections.map((entry): SidebarItemConfig => ({type: 'link', label: entry.label, href: entry.to})),
      }]),
  ],
  ...Object.fromEntries(collections.map(entry => [entry.directory, [
    {type: 'link', label: allContents.label, href: allContents.to},
    collectionSidebar(entry),
  ]])),
};

export interface CategoryNavigationItem {
  label: string;
  href?: string;
  items: CategoryNavigationItem[];
}

export function categoryNavigationPlugin(): Plugin {
  return {
    name: 'category-navigation',
    async allContentLoaded({allContent, actions}) {
      const content = allContent['docusaurus-plugin-content-docs']?.default as LoadedContent;
      const version = content.loadedVersions[0];
      const docs = new Map(version.docs.map(doc => [doc.id, doc.permalink]));
      function categoryItems(items: (typeof version.sidebars)[string]): CategoryNavigationItem[] {
        return items.flatMap(item => {
          if (item.type !== 'category') return [];
          const href = item.link?.type === 'doc'
            ? docs.get(item.link.id)
            : item.link?.type === 'generated-index' ? item.link.permalink : undefined;
          return [{label: item.label, href, items: categoryItems(item.items)}];
        });
      }
      const tree = navigation.flatMap(group => {
        const items = group.collections.flatMap(entry => categoryItems(version.sidebars[entry.directory]));
        return group.to ? items : [{label: group.label, items}];
      });
      actions.setGlobalData(tree);
    },
  };
}

export const footerItems = [
  allContents,
  ...navigation.flatMap(group => group.collections.map(({label, to}) => ({label, to}))),
];