import {readFileSync, readdirSync} from 'node:fs';
import path from 'node:path';
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

type SidebarItemConfig = Extract<SidebarsConfig[string], unknown[]>[number];

interface CategoryMetadata {
  label: string;
  position?: number;
  collapsed?: boolean;
  link: {type: 'doc'; id: string} | {type: 'generated-index'; slug?: string};
}

interface NavigationLink {
  label: string;
  to: string;
}

interface Collection extends NavigationLink {
  directory: string;
  docId: string;
  collapsed: boolean;
}

function categories(directory: string) {
  return readdirSync(path.join(__dirname, 'docs', directory), {withFileTypes: true})
    .filter(entry => entry.isDirectory())
    .map(entry => ({
      directory: `${directory}/${entry.name}`,
      metadata: JSON.parse(readFileSync(
        path.join(__dirname, 'docs', directory, entry.name, '_category_.json'), 'utf8',
      )) as CategoryMetadata,
    }))
    .sort((left, right) => (left.metadata.position ?? Infinity) - (right.metadata.position ?? Infinity)
      || left.directory.localeCompare(right.directory));
}

export const collections: Collection[] = categories('courses').map(({directory, metadata}) => {
  if (metadata.link.type !== 'doc') {
    throw new Error(`Navigation collection ${directory} requires a doc landing page`);
  }
  return {
    directory,
    label: metadata.label,
    to: `/${directory}`,
    docId: metadata.link.id.startsWith(`${directory}/`)
      ? metadata.link.id : `${directory}/${metadata.link.id}`,
    collapsed: metadata.collapsed ?? true,
  };
});

function collection(directory: string): Collection {
  const result = collections.find(entry => entry.directory === directory);
  if (!result) throw new Error(`Missing navigation collection ${directory}`);
  return result;
}

const books = collection('courses/books');
const calculator = collection('courses/calculator');
const courses = collections.filter(entry => entry !== books && entry !== calculator);
const courseGroup = JSON.parse(readFileSync(
  path.join(__dirname, 'docs/courses/_category_.json'), 'utf8',
)) as {label: string; collapsed?: boolean};
const bookSubjects: NavigationLink[] = categories(books.directory).map(({directory, metadata}) => {
  if (metadata.link.type !== 'generated-index' || !metadata.link.slug) {
    throw new Error(`Book subject ${directory} needs an explicit generated-index slug for shared navigation`);
  }
  return {label: metadata.label, to: metadata.link.slug};
});

const allContents: NavigationLink = {label: 'All contents', to: '/'};
export const navigation = [
  {label: courseGroup.label, collections: courses, links: courses},
  {label: books.label, collections: [books], to: books.to, links: [books, ...bookSubjects]},
  {label: calculator.label, collections: [calculator], to: calculator.to},
];

function collectionSidebar(entry: Collection): SidebarItemConfig {
  return {
    type: 'category',
    label: entry.label,
    collapsed: entry.collapsed,
    link: {type: 'doc', id: entry.docId},
    items: [{type: 'autogenerated', dirName: entry.directory}],
  };
}

export const navigationSidebar: SidebarItemConfig[] = [
  {type: 'doc', label: allContents.label, id: 'home'},
  ...navigation.flatMap((group): SidebarItemConfig[] => group.to
    ? group.collections.map(collectionSidebar)
    : [{
      type: 'category',
      label: group.label,
      collapsed: courseGroup.collapsed ?? false,
      items: group.collections.map(collectionSidebar),
    }]),
];

function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, character => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  })[character]!);
}

export function navbarItems(baseUrl: string) {
  const href = (route: string) => `${baseUrl.replace(/\/$/, '')}/${route.replace(/^\//, '')}`;
  return [
    {...allContents},
    ...navigation.map(group => group.links ? {
      type: 'html' as const,
      className: 'contentsNestedGroup',
      value: `<details><summary>${escapeHtml(group.label)}</summary><div class="contentsNestedLinks">${
        group.links.map(link => `<a href="${escapeHtml(href(link.to))}">${escapeHtml(link.label)}</a>`).join('')
      }</div></details>`,
    } : {label: group.label, to: group.to!}),
  ];
}

export const footerItems = [
  allContents,
  ...navigation.flatMap(group => group.collections.map(({label, to}) => ({label, to}))),
];